namespace Jarvis.Plugins.Developer;

/// <summary>
/// Built-in project scaffolds for JARVIS STUDIO. Every template ships a buildable source tree
/// plus a self-contained test so <c>developer.test</c> works without pulling external packages.
/// </summary>
public static class ProjectTemplates
{
    /// <summary>Available template ids and their human-readable labels.</summary>
    public static IReadOnlyDictionary<string, string> Templates { get; } = new Dictionary<string, string>
    {
        ["dotnet-console"] = ".NET console app (C#)",
        ["node-app"] = "Node.js application (JavaScript)",
        ["python-app"] = "Python application",
    };

    /// <summary>Validates that a template id exists.</summary>
    public static bool IsKnown(string template) => Templates.ContainsKey(template);

    /// <summary>Scaffolds a project from a template into <paramref name="root"/>.</summary>
    public static void Scaffold(string template, string name, string root)
    {
        switch (template)
        {
            case "dotnet-console":
                ScaffoldDotNet(name, root);
                break;
            case "node-app":
                ScaffoldNode(name, root);
                break;
            case "python-app":
                ScaffoldPython(name, root);
                break;
            default:
                throw new ArgumentException($"Unknown template '{template}'.");
        }
    }

    /// <summary>Returns the default toolchain command for a template action.</summary>
    public static string DefaultCommand(string template, string action)
    {
        return template switch
        {
            "dotnet-console" => action switch
            {
                "build" => "dotnet build",
                "test" => "dotnet run -- --jarvis-test",
                "run" => "dotnet run",
                _ => string.Empty,
            },
            "node-app" => action switch
            {
                "build" => "node --check index.js",
                "test" => "npm test",
                "run" => "npm start",
                _ => string.Empty,
            },
            "python-app" => action switch
            {
                "build" => "python3 -m py_compile main.py",
                "test" => "python3 -m unittest discover -s . -p test_main.py",
                "run" => "python3 main.py",
                _ => string.Empty,
            },
            _ => string.Empty,
        };
    }

    private static void ScaffoldDotNet(string name, string root)
    {
        string safeName = Sanitize(name);

        Write(root, $"{safeName}.csproj", $"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net8.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <RootNamespace>{safeName}</RootNamespace>
              </PropertyGroup>
            </Project>
            """);

        Write(root, "Program.cs", """
            namespace {0};

            /// <summary>A small self-testing demo app generated by JARVIS STUDIO.</summary>
            internal static class Program
            {
                public static int Main(string[] args)
                {
                    if (args.Length > 0 && args[0] == "--jarvis-test")
                    {
                        return RunTests();
                    }

                    Console.WriteLine("Hello from JARVIS Studio!");
                    Console.WriteLine($"2 + 3 = {Add(2, 3)}");
                    return 0;
                }

                private static int RunTests()
                {
                    int passed = 0;
                    Check(Add(2, 3) == 5, "Add(2, 3) == 5");
                    Check(Add(-1, 1) == 0, "Add(-1, 1) == 0");
                    Check(Multiply(3, 4) == 12, "Multiply(3, 4) == 12");
                    Console.WriteLine($"{passed} test(s) passed.");
                    return 0;

                    void Check(bool condition, string name)
                    {
                        if (!condition)
                        {
                            Console.WriteLine($"FAIL: {name}");
                            Environment.Exit(1);
                        }

                        Console.WriteLine($"PASS: {name}");
                        passed++;
                    }
                }

                private static int Add(int a, int b) => a + b;

                private static int Multiply(int a, int b) => a * b;
            }
            """.Replace("{0}", safeName));
    }

    private static void ScaffoldNode(string name, string root)
    {
        string safeName = Sanitize(name).ToLowerInvariant();

        Write(root, "package.json", """
            {
              "name": "__NAME__",
              "version": "1.0.0",
              "private": true,
              "scripts": {
                "start": "node index.js",
                "test": "node --test"
              }
            }
            """.Replace("__NAME__", safeName));

        Write(root, "index.js", """
            function add(a, b) {
              return a + b;
            }

            function multiply(a, b) {
              return a * b;
            }

            console.log(`Hello from JARVIS Studio!`);
            console.log(`2 + 3 = ${add(2, 3)}`);

            module.exports = { add, multiply };
            """);

        Write(root, "index.test.js", """
            const { test } = require('node:test');
            const assert = require('node:assert');
            const { add, multiply } = require('./index');

            test('add(2, 3) === 5', () => assert.strictEqual(add(2, 3), 5));
            test('add(-1, 1) === 0', () => assert.strictEqual(add(-1, 1), 0));
            test('multiply(3, 4) === 12', () => assert.strictEqual(multiply(3, 4), 12));
            """);
    }

    private static void ScaffoldPython(string name, string root)
    {
        _ = name;

        Write(root, "main.py", """
            def add(a, b):
                return a + b


            def multiply(a, b):
                return a * b


            if __name__ == "__main__":
                print("Hello from JARVIS Studio!")
                print(f"2 + 3 = {add(2, 3)}")
            """);

        Write(root, "test_main.py", """
            import unittest

            from main import add, multiply


            class TestDemo(unittest.TestCase):
                def test_add_positive(self):
                    self.assertEqual(add(2, 3), 5)

                def test_add_negative(self):
                    self.assertEqual(add(-1, 1), 0)

                def test_multiply(self):
                    self.assertEqual(multiply(3, 4), 12)


            if __name__ == "__main__":
                unittest.main()
            """);
    }

    private static void Write(string root, string relativePath, string content)
    {
        string fullPath = Path.Combine(root, relativePath);
        string? directory = Path.GetDirectoryName(fullPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(fullPath, content);
    }

    private static string Sanitize(string name)
    {
        string safe = new string(name.Select(character => char.IsLetterOrDigit(character) ? character : '_').ToArray());
        if (safe.Length == 0 || !char.IsLetter(safe[0]))
        {
            safe = "App" + safe;
        }

        return safe;
    }
}
